# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 434b9778a71b0fb3f8d9420f4cc60bf8b0032f4ff4378a7d743b0f0591d28dd6b5c2606980ba65cbc97421d21c1650d95cd4d1ccf490e8910536be898c59f154

test:
  secret_key_base: 5b57eeceb451fb8fd49cde689bc2742ec641f01123a4e5122cfa77683958b03fccdb96bdcc17d4df5c7e404225e980d58933a3cd774c1887ff8c433b050d55d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
